name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Database Environment
        run: echo "DB_CONNECTION=sqlite" > .env

      - name: Run migrations
        run: php artisan migrate --force

      - name: Cache vendor folder
        uses: actions/cache@v2
        with:
          path: |
            vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Restore Cached vendor folder
        uses: actions/cache@v2
        with:
          path: |
            vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run Tests
        run: php artisan test

  stan:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Restore Cached vendor folder
        uses: actions/cache@v2
        with:
          path: |
            vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Run Stan
        run: vendor/bin/phpstan analyze app

  fail-job:
    runs-on: ubuntu-latest
    needs: ["test", "stan"]

    steps:
      - name: Invalid Command
        run: mucahit -p 12345

  clean-up:
    runs-on: ubuntu-latest

    needs: ["test", "stan"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Restore Cached vendor folder
        uses: actions/cache@v2
        with:
          path: |
            vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Remove Dev Dependencies
        run: composer install --no-interaction --prefer-dist --no-dev

  deploy:
    runs-on: ubuntu-latest

    needs: ["clean-up", "fail-job"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      - name: Known Host
        run: ssh-keyscan 185.241.63.153 >> ~/.ssh/known_hosts

      - name: Run deploy
        run: php vendor/bin/envoy run deploy
